export const Endpoints = {
    "LOGIN":"/login",
    "REGISTER":"/register",
    "ACCOUNT":"/account",
    "FREELANCERS":"/freelancers",
    "FREELANCER":"/freelancer",
    "JOBS":"/jobs",
    "JOB":"/job",
    "OFFER":"/offer",
    "OFFER_STATUS":"/offer/status",
    "OFFERS_FREELANCER":"/offer-freelancer",
    "OFFER_FREELANCER_JOB":"/offer-freelancer-job",
    "PORTFOLIO":"/portfolio",
    "PORTFOLIORECRUITER":"/portfolio-recruiter",
    "PROJECTS":"/projects",
    "PROJECT":"/project",
    "RECRUITER": "/recruiter",
    "SKILL":"/skills",
    "GENRE":"/genre",
    "TOPUP":"/payment/topup",
    "BALANCE":"/payment/balance",
    "PAYMENTHISTORY":"/payment/payment-history",
    "MESSAGE":"/message",
    "MESSAGEBYTARGET":"/message/job",
    "MESSAGEJOBID":"/message/by-job-id",
    "NEWMESSAGE":"/message/new",
    "RATING": "/rating"
}